---
config:
  theme: default
id: ff9a3fa6-ea00-463b-a128-f18885db0408
---
mindmap
((mindmap))
  Origins
    Long history
    ::icon(fa fa-book)
    Popularization
      British popular psychology author Tony Buzan
  Research
    On effectiveness<br>and features
    On Automatic creation
      Uses
        Creative techniques
        Strategic planning
        Argument mapping
  Tools
    Pen and paper
    Mermaid
  Darpan
  Piyush
    Raghav
    n23
  Jayant
  n20
  n21
  n22